### PR TITLE
19019: Change 'proxy_ca_certificate' to sensitive

### PR DESCRIPTION
**Pull request by zhiqiangjin**

### CODE REVIEW

**Review by shuoliugit — APPROVED** [review]

**Review by CyrusJavan — APPROVED** [review]

**Comment by arvindsree** [comment]
CA certificate doesn't need to be sensitive. This the public CA certificate used for validating the Proxy server itself

**Comment by zhiqiangjin** [comment]
Since this is the public CA certificate used for validating the Proxy server itself, CA certificate doesn't need to be sensitive.

**Comment by zhiqiangjin** [comment]
After discussion, should change it to sensitive.

**Comment by zhiqiangjin** [comment]
CA certificate doesn't need to be sensitive. This is the public CA certificate used for validating the Proxy server itself. Fixed from backend side to return certificate information. Close this PR.

**Pull request closed without merging**
