### PR TITLE
Fix import of edge device

### PR DESCRIPTION
**Pull request by CyrusJavan**
Will update with a Jira ticket when created.

### CODE REVIEW

**Comment by rpanzer-aviatrix** [comment]
Maybe you can use AVX-54454?
This PR seems to be a superset of #1992

**Review by dnardo — CHANGES_REQUESTED** [review]
Already had a fix for this, just needed a review.
https://github.com/AviatrixSystems/terraform-provider-aviatrix/pull/1992

**Comment by dnardo** [comment]
> Already had a fix for this, just needed a review. #1992

Also neo is deprecated resource we don't need to fix that one. In fact it should be removed for 3.2

**Comment by CyrusJavan** [comment]
@dnardo @rpanzer-aviatrix Thanks for the info, will close this in favor of the existing PR.

**Pull request closed without merging**
