### PR TITLE
[WIP]Update import to owner AviatrixSystems

### PR DESCRIPTION
**Pull request by malachany**
- Update owner name in import of main.go
- Update docs to reflect update

Updating to fix issues when importing with go elsewhere. This should be the owner in github.com to follow golang convention. For example, using `go get` will now work correctly.

### CODE REVIEW

**Comment by mikecook** [comment]
If/when Hashicorp accepts this project into terraform-providers they'll have to do updates anyway, for example correcting the README. This project should work properly with go tooling in the meantime.

This would also be good time to start tagging release versions, perhaps one before and one after this merge, and then put them in the changelog file.

**Comment by arvindsree** [comment]
Totally agree. The only downside to this is that ALL the existing people using the provider have to update their folder structure.

**Comment by malachany** [comment]
@arvindsree, I don't see why anyone would need to change their folder structure. The build puts in `$GOPATH/bin` and then the instructions state to add that to terraform config file from `$GOPATH/bin`. 

Only issue I see is that they will need to use the new instructions to not copy around the directory.

**Comment by arvindsree** [comment]
main.go will import from  $GOPATH/src/github.com/AviatrixSystems/terraform-provider-aviatrix/aviatrix
This will give errors for current users having source code at $GOPATH/src/github.com/terraform-providers/terraform-provider-aviatrix

**Comment by mikecook** [comment]
The only reason this breaks users at all is because you are importing from paths that do not exist. You're not under terraform-providers.

When you make up a non-existent import path, of course it's going to break. So you've had your users work around that broken import path by having them manually move folders around to your pretend path. This is wrong. 

What I can't understand is why you not only persist in this broken situation, but compound it. Fix it once, and it'll never be broken again. We'll get this PR updated so that even if you don't merge it, other users can pull it in to fix this brokenness.

**Comment by mikecook** [comment]
Also, could you please stop force-pushing to master? That's also not ok.

**Comment by arvindsree** [comment]
Seems like the force push was accidental. Not sure how it happened

Like we said earlier, for customers who do not understand go or how imports work and have set everything up according to our docs, it will cause breakage for people who just do a git pull and try to compile and cause unnecessary support tickets.

We were ready for provider acceptance(Ref: #2) months earlier, which would move the code to the terraform-providers github. We would prefer fixing it this way to have the least impact on the existing users.

**Comment by arvindsree** [comment]
Hi,

Thank you for being patient with us. The github repository has been moved here https://github.com/terraform-providers/terraform-provider-aviatrix/ .
If you use the version from there, this Pull Request is not necessary

Thanks,
Arvind

**Pull request closed without merging**
