### PR TITLE
18245: add guard duty features

### PR DESCRIPTION
**Pull request by CyrusJavan**
- Add resource `aviatrix_aws_guard_duty` that configures a single account/region pair
- Add `aws_guard_duty_scanning_interval` to controller_config resource

### CODE REVIEW

**Review by shuoliugit — COMMENTED** [review]
Does the file aviatrix.erb need to be updated?

**Comment by CyrusJavan** [comment]
> Does the file aviatrix.erb need to be updated?

@shuoliugit Actually I need to confirm. Now that I think about it, after the move the the Terraform Registry I don't think Hashicorp is still reading the .erb file to generate the sidebar

**Comment by shuoliugit** [comment]
> > Does the file aviatrix.erb need to be updated?
> 
> @shuoliugit Actually I need to confirm. Now that I think about it, after the move the the Terraform Registry I don't think Hashicorp is still reading the .erb file to generate the sidebar

ok, if the .erb file is not needed anymore, maybe we can remove it later.

**Comment by CyrusJavan** [comment]
> > > Does the file aviatrix.erb need to be updated?
> > 
> > 
> > @shuoliugit Actually I need to confirm. Now that I think about it, after the move the the Terraform Registry I don't think Hashicorp is still reading the .erb file to generate the sidebar
> 
> ok, if the .erb file is not needed anymore, maybe we can remove it later.

The docs are now totally generated from the static markdown files, this Ruby (.erb) file is no longer used. See https://www.terraform.io/docs/registry/providers/docs.html. I've opened a Mantis to work on this later https://mantis.aviatrix.com/mantisbt/view.php?id=18944

**Comment by CyrusJavan** [comment]
They also released a tool for auto-generating documentation that we should look into. https://github.com/hashicorp/terraform-plugin-docs

**Review by shuoliugit — APPROVED** [review]

**Pull request merged**
