### PR TITLE
use go mod

### PR DESCRIPTION
**Pull request by mikecook**
- Commands used to generate this patch:
  GO111MODULE=on go mod init
  GO111MODULE=on go mod tidy
  GO111MODULE=on go mod vendor

### CODE REVIEW

**Comment by arvindsree** [comment]
Hello Mike,

Thanks for the PR.
What is the advantage of using go mod? We already have vendor/update_vendor.py to vendor the dependencies and create the vendor.json in the format required by Hashicorp

Also, The AviatrixSystems/go-aviatrix is a special dependancy as well, where the original version is kept in this repo and the copy of this auto-pushed to AviatrixSystems/go-aviatrix

Thanks,
Arvind

**Comment by mikecook** [comment]
go mod is on track to become the official tool for dependency management within golang. See https://github.com/golang/go/wiki/Modules

Also, what you're doing autopushing code from here to the repo you're actually referencing the library from sounds very wrong, but I haven't read that script.

**Comment by arvindsree** [comment]
We wanted to deprecate the go-aviatrix completely and integrate it into the provider as it is very tightly coupled with each of the provider changes. However, some people were using the go-aviatrix library alone and wanted it separately, that is why we decided to keep it as a copy.  (We originally tried git submodules but that was very inconvenient)

Using go mod seems to be fine. But there needs to be a way to prevent go-aviatrix library from being overwritten. Until then we can continue to use  "go get" which is leveraged by vendor/update_vendor.py

**Comment by mikecook** [comment]
With as much dev as you do against both, you should just move the go-aviatrix lib out of vendor and into a subdir of root (github.com/AviatrixSystems/go-aviatrix/), and import the lib from there. Then update the other repo's readme to tell people it is deprecated and to update their imports to the new path. You'll have to leave the other repo there or you'll break existing users, but you could also add warnings to the code that it is deprecated and the new import path. No need to update the other repo after that.

**Comment by arvindsree** [comment]
Thanks for the idea. That makes sense. We will work on that and then you can re-run this to exclude the go-aviatrix. We will probably still maintain the go-aviatrix library through auto push

**Comment by mikecook** [comment]
Why would you maintain it in two places? Anyone can import it from the new place and it will work the same. If you just make a subdir here, then you won't need auto push...

Here's an example from within your own code of importing a lib that is a subdir of a larger project
https://github.com/AviatrixSystems/terraform-provider-aviatrix/blob/master/aviatrix/data_source_aviatrix_account.go#L8
```"github.com/hashicorp/terraform/helper/schema"```
You are just importing their schema, not all of their terraform.

After you moved go-aviatrix to this repo (not vendored) it would be an import line change of
```"github.com/AviatrixSystems/go-aviatrix/goaviatrix"```
to
```"github.com/AviatrixSystems/terraform-provider-aviatrix/go-aviatrix/goaviatrix"```
And anyone else who imported just that lib could do the same.

**Comment by arvindsree** [comment]
I guess it would be redundant. In that case, we will only have one version maintained in this repo

**Comment by mikecook** [comment]
Moving the go-aviatrix lib to inside the provider alleviates the need for this. Closing. See #97 .

**Comment by mikecook** [comment]
Since we build from tags, when there isn't a go.mod (or any golang dependency system), when go fetches the go-aviatrix deps, it gets them from master, which will have changed since older tags. This patch allows us to build against specific tags. 

If this patch were merged, then the version of go.mod that will be tagged at the same time as the rest of the repo will always allow tagged versions to get their correct deps, even if the tag is old.

**Comment by arvindsree** [comment]
Thanks.
Already supported from R1.16 as per #549

**Pull request closed without merging**
